spring:
  application:
    name: springboot-aws-sqs-test
  cloud:
    aws: # SqsTemplate configuration
      credentials:
        access-key: test-key
        secret-key: test-secret
      region:
        static: us-east-1 # A static value for region used by auto-configured AWS clients as AWS credentials are valid in a context of a region.
        auto: false
sqs:
  endpoint: http://localhost:4566
  queueName: DemoSQS